[profile.ci.fuzz]
runs = 10_000

[dependencies]
forge-std = { version = "1.9.3", url = "https://soldeer-revisions.s3.amazonaws.com/forge-std/1_9_3_30-09-2024_08:27:09_forge-std-1.9.zip" }
"@openzeppelin-contracts" = "5.0.2"
